---
# deploy-base.yml

## this doesnt seem to propogate between roles, even when hosts: localhost
#- hosts: localhost
#  vars:
#    name: ami-builder-base
#    myp_type: base

- name: Find existing instance(s)
  hosts: "tag_Name_ami_build_base*"
  gather_facts: false
  tags: find
  tasks:
    - name: Add to old-ami-build-base group
      group_by:
        key: old-ami-build-base

- name: Launch new build base
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - role: launch-base
      name: ami-build-base
      myp_type: base

- name: Provision new build base
  hosts: ami-build-base #this is an ansible group created in the launch-base role
  roles:
    - platform-base
    - rbenv-ruby
    - myp-passenger
    - myp-papertrail
    - { role: datadog, become: yes, datadog_api_key: "89205a0859d3d8eaca4e27516899a848" }

- hosts: ami-build-base #this is an ansible group created in the launch-base role
  connection: local
  gather_facts: yes
  roles:
    - role: build-ami
      name: ami-build-base
      myp_type: base
#    - create-launch-configuration
#    - load-balancer
#    - auto-scaling
#    - dns

- hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - { role: delete-old-amis, name: ami-build-base, myp_type: base }
#    - delete-old-launch-configurations

- hosts: old-ami-build-base
  connection: local
  gather_facts: false
  roles:
    - terminate
