---
# roles/rbenv-ruby/tasks/main.yml

# set up and install supporting packages
- name: Include env vars
  include_vars: "{{ rbenv.env }}.yml"
- debug: var=rbenv.env
- debug: var=rbenv_group
- debug: var=rbenv_root

- include: apt_build_depends.yml 
  when: ansible_pkg_mgr == 'apt'
- include: yum_build_depends.yml
  when: ansible_pkg_mgr == 'yum'
- include: homebrew_build_depends.yml
  when: ansible_os_family == 'Darwin'

- name: Set rbenv_owner
  set_fact: 'rbenv_owner={{ rbenv_owner | default("root", true) }}'

# system: rbenv install
- name: Checkout rbenv_repo for system install
  become: yes
  become_user: '{{ rbenv_owner }}'
  git: >
    repo={{ rbenv_repo }}
    dest={{ rbenv_root }}
    version={{ rbenv.version }}
    accept_hostkey=yes
    force=yes
  when: rbenv.env == "system"
  tags:
    - rbenv-ruby

- name: Create plugins directory for system install
  become: yes
  become_user: '{{ rbenv_owner }}'
  file: state=directory path={{ rbenv_root }}/plugins
  when: rbenv.env == "system"
  tags:
    - rbenv-ruby

- name: Install plugins for system install
  become: yes
  become_user: '{{ rbenv_owner }}'
  git: >
    repo={{ item.repo }}
    dest={{ rbenv_root }}/plugins/{{ item.name }}
    version={{ item.version }}
    accept_hostkey=yes
    force=yes
  with_items: "{{ rbenv_plugins }}"
  when: rbenv.env == "system"
  tags:
    - rbenv-ruby
###

# system: rbenv permission
- name: Set group ownership of content under rbenv_root
  shell:
    find '{{ rbenv_root }}'
      \( -iname ".git" -prune \) -o
      ! -group '{{ item }}'
      -exec chgrp -v '{{ item }}' {} + | head -n 1
  become: yes
  with_items: '{{ rbenv_group }}'
  when:
    - rbenv.env == "system"
    - rbenv_group is defined
    - rbenv_group != None
  register: rbenv_chgrp
  changed_when: '"changed group" in rbenv_chgrp.stdout'
  tags:
    - rbenv-ruby

- name: Set group permissions of content under rbenv_root
  shell:
    find '{{ rbenv_root }}'
      \( -iname ".git" -prune \) -o
      -type d ! -perm -g+s
      -exec chmod -v g+rwxs {} + | head -n 1
  become: yes
  when:
    - rbenv.env == "system"
    - rbenv_group is defined
    - rbenv_group != None
  register: rbenv_chmod
  changed_when: '"changed from" in rbenv_chmod.stdout'
  tags:
    - rbenv-ruby
###

# != system: rbenv install
- name: Checkout rbenv_repo for user install
  with_items: "{{ rbenv_users }}"
  become: yes
  become_user: "{{ item }}"
  git: >
    repo={{ rbenv_repo }}
    dest={{ rbenv_root }}
    version={{ rbenv.version }}
    accept_hostkey=yes
    force=yes
  when: rbenv.env != "system"
#  ignore_errors: yes
  tags:
    - rbenv-ruby

- name: Create plugins directory for user install
  with_items: "{{ rbenv_users }}"
  become: yes
  become_user: "{{ item }}"
  file: state=directory path={{ rbenv_root }}/plugins
  when: rbenv.env != "system"
#  ignore_errors: yes
  tags:
    - rbenv-ruby

- name: Install plugins for user install
  with_nested:
    - "{{ rbenv_users }}"
    - "{{ rbenv_plugins }}"
  become: yes
  become_user: "{{ item[0] }}"
  git: >
    repo={{ item[1].repo }}
    dest={{ rbenv_root }}/plugins/{{ item[1].name }}
    version={{ item[1].version }}
    accept_hostkey=yes
    force=yes
  when: rbenv.env != "system"
#  ignore_errors: yes
  tags:
    - rbenv-ruby
###

# rbenv initialization
- name: Add rbenv initialization to profile system-wide
  become: yes
  template: src=rbenv.sh.j2 dest=/etc/profile.d/rbenv.sh owner=root group=root mode=0755
  when:
    - ansible_os_family != 'OpenBSD' and ansible_os_family != 'Darwin'
  tags:
    - rbenv-ruby

# system: default gems
- name: Set default-gems for system install
  copy: src=default-gems dest={{ rbenv_root }}/default-gems
  become: yes
  when:
    - rbenv.env == "system"
    - default_gems_file is not defined
#  ignore_errors: yes
  tags:
    - rbenv-ruby

# != system
- name: Set default-gems for for user install
  with_items: "{{ rbenv_users }}"
  become: yes
  become_user: "{{ item }}"
  copy: src=default-gems dest={{ rbenv_root }}/default-gems
  when:
    - not "system" == "{{ rbenv.env }}"
    - default_gems_file is not defined
#  ignore_errors: yes
  tags:
    - rbenv-ruby

- name: Set custom default-gems for user install
  with_items: "{{ rbenv_users }}"
  become: yes
  become_user: "{{ item }}"
  copy: src={{ default_gems_file }} dest={{ rbenv_root }}/default-gems
  when:
    - not "system" == "{{ rbenv.env }}"
    - default_gems_file is defined
#  ignore_errors: yes
  tags:
    - rbenv-ruby

- name: Set gemrc for user install
  with_items: "{{ rbenv_users }}"
  become: yes
  become_user: "{{ item }}"
  copy: src=gemrc dest=~/.gemrc
  when: rbenv.env != "system"
#  ignore_errors: yes
  tags:
    - rbenv-ruby

- name: Set vars for user install
  with_items: "{{ rbenv_users }}"
  become: yes
  become_user: "{{ item }}"
  copy: src=vars dest={{ rbenv_root }}/vars
  when: rbenv.env != "system"
#  ignore_errors: yes
  tags:
    - rbenv-ruby
###

# system: install and set ruby
- name: Check ruby {{ rbenv.ruby_version }} installed for system install
  become: yes
  shell: $SHELL -lc "rbenv versions | grep {{ rbenv.ruby_version }}"
  register: ruby_installed
  changed_when: false
  ignore_errors: yes
  always_run: yes
  when: rbenv.env == "system"
  tags:
    - rbenv-ruby
- debug: var=ruby_installed

- name: Install ruby {{ rbenv.ruby_version }} (system install)
  shell: bash -lc "rbenv install {{ rbenv.ruby_version }}"
  become: yes
  when:
    - rbenv.env == "system"
    - ruby_installed.rc != 0
  tags:
    - rbenv-ruby

- name: Check if current ruby version is {{ rbenv.ruby_version }} (system install)
  shell: $SHELL -lc "rbenv version | cut -d ' ' -f 1 | grep -Fx '{{ rbenv.ruby_version }}'"
  register: ruby_selected
  changed_when: false
  ignore_errors: yes
  always_run: yes
  when: rbenv.env == "system"
  tags:
    - rbenv-ruby
- debug: var=ruby_selected

- name: Set ruby {{ rbenv.ruby_version }} for system install
  become: yes
  shell: bash -lc "rbenv global {{ rbenv.ruby_version }} && rbenv rehash"
  when:
    - rbenv.env == "system"
    - ruby_selected.rc != 0
  tags:
    - rbenv-ruby
###

# != system: install and set ruby
- name: Check if ruby {{ rbenv.ruby_version }} is installed (user install)
  with_items: "{{ rbenv_users }}"
  become: yes
  become_user: "{{ item }}"
  shell: $SHELL -lc "rbenv versions | grep {{ rbenv.ruby_version }}"
  register: ruby_installed
  changed_when: false
  ignore_errors: yes
  always_run: yes
  when: rbenv.env != "system"
  tags:
    - rbenv-ruby
- debug: var=ruby_installed
- debug: var=ruby_installed.results

- name: Install ruby {{ rbenv.ruby_version }} (user install)
  with_together:
    - "{{ ruby_installed.results }}"
    - "{{ rbenv_users }}"
  become: yes
  become_user: "{{ item[1] }}"
  shell: $SHELL -lc "rbenv install {{ rbenv.ruby_version }}"
  when:
    - rbenv.env != "system"
    - item[0].rc != 0
#  ignore_errors: yes
  tags:
    - rbenv-ruby

- name: Check if current ruby version is {{ rbenv.ruby_version }}  (user install)
  with_items: "{{ rbenv_users }}"
  become: yes
  become_user: "{{ item }}"
  shell: $SHELL -lc "rbenv version | cut -d ' ' -f 1 | grep -Fx '{{ rbenv.ruby_version }}'"
  register: ruby_selected
  changed_when: false
  ignore_errors: yes
  always_run: yes
  when: rbenv.env != "system"
  tags:
    - rbenv-ruby
- debug: var=ruby_selected

- name: Set ruby {{ rbenv.ruby_version }} (user install)
  with_together:
    - "{{ ruby_selected.results }}"
    - "{{ rbenv_users }}"
  become: yes
  become_user: "{{ item[1] }}"
  shell: $SHELL -lc "rbenv global {{ rbenv.ruby_version }} && rbenv rehash"
  when:
    - rbenv.env != "system"
    - item[0].rc != 0
  ignore_errors: yes
  tags:
    - rbenv-ruby
###

# != system: install bundler
# shouldnt have to do this, need to fix default gems section for user install
- name: install bundler (user install)
  shell: $SHELL -lc "gem install bundler"
  when: rbenv.env != "system"