---
# roles/passenger-enterprise/tasks/pkg.yml

- name: pkg - Install apache passenger packages
  apt: pkg={{ item }} state={{ passenger_pkgs_state }}
  become: true
  with_items:
    - apache2-dev
    - apache2-mpm-worker
    - libapache2-mod-passenger-enterprise
  notify: apache restart
  when: passenger_webserver == "apache"

## nginx not yet configured for mypizza
- name: pkg - install nginx passenger packages
  apt: pkg={{ item }} state={{ passenger_pkgs_state }}
  become: true
  with_items:
    - nginx-extras
    - passenger
  notify: nginx restart
  when: passenger_webserver == "nginx"

## standalone not yet configured for mypizza
- name: pkg - install standalone passenger packages
  apt: pkg={{ item }} state={{ passenger_pkgs_state }}
  with_items:
    - passenger
  when: passenger_webserver == "standalone"

- name: pkg - fix passenger utils shebang
  lineinfile:
    dest: "{{ item }}"
    regexp: '^#\!/usr/bin/ruby\s*'
    line: "#!/usr/bin/env ruby"
    backrefs: yes
    state: present
  with_items:
    - /usr/sbin/passenger-memory-stats
    - /usr/sbin/passenger-status
  when: passenger_pkgs_fix_shebang

