---
# roles/papertrail/tasks/main.yml

- name: Create service account for Papertrail
  user: name=papertrail
        system=yes
        home=/var/lib/papertrail
        shell=/bin/false
        state=present
  become: yes

- name: Download Papertrail PEM
  get_url: url="https://papertrailapp.com/tools/papertrail-bundle.pem"
           dest="/etc/papertrail-bundle.pem"
           sha256sum="7019189e20ed695e9092e67d91a3b37249474f4c4c6355193ce6d2cb648f147c"
           mode=0644
  become: yes

- name: Install TLS support for Rsyslog
  apt: name=rsyslog-gnutls state=present
  become: yes

- name: Download remote_syslog
  get_url: url="https://github.com/papertrail/remote_syslog2/releases/download/v{{ papertrail_version }}/remote_syslog_linux_amd64.tar.gz"
           dest="/usr/local/src/remote_syslog_{{ papertrail_version }}_linux_amd64.tar.gz"
  become: yes

- name: Extract remote_syslog
  unarchive: src="/usr/local/src/remote_syslog_{{ papertrail_version }}_linux_amd64.tar.gz"
             dest=/opt
             copy=no
             owner=root
             group=root
             creates=/opt/remote_syslog/remote_syslog
  become: yes

- name: Configure Rsyslog to use Papertrail
  template: src="30-papertrail.conf.j2"
            dest="/etc/rsyslog.d/30-papertrail.conf"
  notify:
    - Restart Rsyslog
  become: yes

- name: Configure Papertrail service definition
  template: src="remote_syslog.conf.j2"
            dest="/etc/init/remote_syslog.conf"
  notify:
    - Restart remote_syslog
  become: yes
